import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Coin Viewer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="antialiased scroll-smooth">
      <body className="">{children}</body>
    </html>
  );
}
